### PR TITLE
SimpleGlobalState class made json-serializable

### PR DESCRIPTION
**Pull request by unboxedtype**
I think it is not a bad idea to make SimpleGlobalState class JSON-serializable. I use this functionality in my own development and maybe others will find it useful too.

### CODE REVIEW

**Comment by unboxedtype** [comment]
Have any idea why the compiler complains on those type conversions giving that in my setting everything compiles just fine. I use g++ 9.1.1, and circleci use 7.4.0, maybe I have a more recent stl libraries?

**Comment by eddyashton** [comment]
> Have any idea why the compiler complains on those type conversions giving that in my setting everything compiles just fine. I use g++ 9.1.1, and circleci use 7.4.0, maybe I have a more recent stl libraries?

I'm using 7.4.0 and getting the same error, coming from `j["accounts"] = s.accounts` in `simpleglobalstate.cpp`. These template errors are always horrible to parse, and Boost makes them much worse.

I _think_ the problem comes from trying to convert `uint256_t` (the key of the accounts table) to `std::string` (all json object keys need to be strings, so nlohmann is trying to do this conversion).

I'm guessing it works for you as you're using a different Boost version, with different string conversion precedence. The CI is using 1.67.

For a general fix, you'll probably need to create an `nlohmann::json::object()` manually and then add each of the accounts entries to it, and make sure this matches the format that `from_json` is expecting.

Something like
```
auto o = nlohmann::json::object();
for (const auto& p: s.accounts)
{
  o[to_hex_str(p.first)] = p.second;
}
j["accounts"] = o;
```

**Comment by unboxedtype** [comment]
Now everything compiles, but tests fail, however everything passes on my side. Is it possible to elaborate on why tests fail in CI?

**Comment by eddyashton** [comment]
> Now everything compiles, but tests fail, however everything passes on my side. Is it possible to elaborate on why tests fail in CI?

I'll create a separate PR to make the CI test failures more verbose, though doctest still gives imprecise errors in many cases. In this case, the error message is:

```
../tests/main.cpp:22:
TEST CASE:  from_json/to_json are mutually inverse

../tests/main.cpp:22: ERROR: test case THREW exception: [json.exception.type_error.302] type must be object, but is array
```

`from_json` for `SimpleGlobalState` expects a json object, but `to_json` has produced an array. nlohmann::json's STL conversion support is described [here](https://github.com/nlohmann/json#conversion-from-stl-containers), I believe this stems from some discrepancy in how Boost's MPI types are auto-converted to strings, but don't have time to investigate further.

**Comment by unboxedtype** [comment]
Thanks! Finally got it working.

**Pull request merged**
